.\" Manpage for ytfind.
.\" Contact lotsof@shitposting.expert to correct errors or typos.
.TH man 1 "21 May 2023" "1.0" "ytfind man page"
.SH NAME
ytfind \- search youtube
.SH SYNOPSIS
ytfind [QUERY]
.SH DESCRIPTION
ytfind is a C program for searching youtube via invidious.

ytfind picks a random instance from a list defined at compile time in config.h
.SH OPTIONS
[QUERY] - query used for searching
.SH EXAMPLES
ytfind never gonna give you up

ytfind test

.SH BUGS
No known bugs.
.SH AUTHOR
305a385 (lotsof@shitposting.expert)
.SH COPYRIGHT
This  is  free  software:  you  are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

Source code is located at https://github.com/305a385/ytfind. Licensed under AGPL version 3.0.

View LICENSE file of root directory in source code
